# Generated by Django 4.2.7 on 2024-02-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playmate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('wallet', models.CharField(blank=True, max_length=100)),
                ('game_category', models.CharField(blank=True, max_length=100)),
                ('headline_message', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
