# Generated by Django 4.2.7 on 2024-02-18 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0002_advertisement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertisement',
        ),
    ]
